cert: vault:arcalos-prod-mgmt/lighthouse-githubapp/cloudbees-cicd:private-key
id: vault:arcalos-prod-mgmt/lighthouse-githubapp/cloudbees-cicd:app-id
secret: vault:arcalos-prod-mgmt/lighthouse-githubapp/cloudbees-cicd:webhook-secret

tenantService:
  url: http://jx-tenant-service

replicaCount: 3

debug: true
