datadog:
  datadog:
    apiKey: vault:arcalos-prod-mgmt/monitoring/datadog-app:apiKey
    appKey: vault:arcalos-prod-mgmt/monitoring/datadog-app:appKey
    clusterName: "{{ .Requirements.cluster.clusterName }}"
    tags:
      - env: prod
      - clustername: "{{ .Requirements.cluster.clusterName }}"
    nonLocalTraffic: true
    collectEvents: true
    leaderElection: true
    logs:
      enabled: true
      containerCollectAll: true
    apmEnabled: true
    processAgentEnabled: false
    acInclude: image:bash image:creds-init image:entrypoint image:git-init image:builder-jx image:jx-tenant-service
    kubeStateMetrics:
      enabled: false
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    confd:
      etcd.yaml: |-
        ad_identifiers:
          - etcd
        init_config:
        instances:
          - url: "https://metrics-server.kube-system/metrics"
  daemonset:
    useHostPort: true
