datadog:
  datadog:
    apiKey: vault:arcalos-prod-mgmt/monitoring/datadog-app:apiKey
    clusterName: "{{ .Requirements.cluster.clusterName }}"
    tags:
      - env:prod
      - clustername:"{{ .Requirements.cluster.clusterName }}"
    nonLocalTraffic: true
    collectEvents: true
    leaderElection: true
    logsEnabled: true
    logsConfigContainerCollectAll: false
    apmEnabled: true
    processAgentEnabled: false
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    confd:
      etcd.yaml: |-
        ad_identifiers:
          - etcd
        init_config:
        instances:
          - url: "https://metrics-server.kube-system/metrics"
  daemonset:
    useHostPort: true
