{{- $prefix := regexFind "^[^.]+." .Requirements.ingress.domain }}
{{- $rootDomain := trimPrefix $prefix .Requirements.ingress.domain }}
jxui:
  gcpSA: vault:arcalos-prod-mgmt/aps-alpha/arcalos-prod-sa:json
  replicaCount: 2
  skipExposeService: true
  sso:
    create: true
    useSSOOperator: false
    connector: arcalos
  roxApiKey: vault:arcalos-prod-mgmt/feature-flag/rox:api-key
  segmentWriteKey: vault:arcalos-prod-mgmt/monitoring/segment:write-key
  service:
    serviceAnnotations:
      fabric8.io/expose: "false"
      fabric8.io/exposeUrl: https://arcalosui{{ .Requirements.ingress.namespaceSubDomain }}{{ $rootDomain }}
    backend:
      initGcpServiceAccount: true
