adminUser:
  password: vault:arcalos-prod-mgmt/adminUser:password
  username: admin
dashboardAuthID: vault:arcalos-prod-mgmt/dashboard/auth:id
dashboardAuthSecret: vault:arcalos-prod-mgmt/dashboard/auth:secret
enableDocker: false
parentDNSZone: jxaas-live-parent
parentDomain: jxaas.live
parentProject: arcalos-domain-name
pipelineUser:
  email: operations+arcalos-admin-bot@googlegroups.com
  token: vault:arcalos-prod-mgmt/pipelineUser:token
  username: arcalos-admin-bot
prow:
  hmacToken: vault:arcalos-prod-mgmt/prow:hmacToken
tenantFolderID: "658956314212"
tenantServiceBasicAuth: vault:arcalos-prod-mgmt/jx-tenant-service/basic-auth:password
